name: Trunk Check

on:
  - pull_request
  - workflow_dispatch

permissions:
  contents: read

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24.9.0
          package-manager-cache: false

      - name: Install required dependencies
        run: npm install

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
